### ISSUE TITLE
Cascade delete causes crash on sync

### ISSUE THREAD

**Issue by ifabijanovic** [Kinvey/swift-sdk#344] opened 2019-01-02 09:26 UTC
Hello, after updating to version 3.21.0 and launching my app on the simulator is I get this crash:

```
2019-01-02 10:16:46.409814+0100 -[Swift._SwiftDeferredNSArray UTF8String]: unrecognized selector sent to instance 0x600003fd0aa0
2019-01-02 10:16:46.427309+0100 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Swift._SwiftDeferredNSArray UTF8String]: unrecognized selector sent to instance 0x600003fd0aa0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001116551bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000110bf3735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000111673f44 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000111659ed6 ___forwarding___ + 1446
	4   CoreFoundation                      0x000000011165bda8 _CF_forwarding_prep_0 + 120
	5   libswiftos.dylib                    0x0000000113c46da9 _os_log_encode + 2441
	6   libswiftos.dylib                    0x0000000113c47245 _swift_os_signpost_with_format + 149
	7   libswiftos.dylib                    0x0000000113c461d0 $S2os0A9_signpost_3dso3log4name0B2ID__ySo0a1_B7_type_ta_SVSo03OS_a1_D0Cs12StaticStringVAA010OSSignpostF0VALs7CVarArg_pdtFySRys5UInt8VGXEfU_ySPys4Int8VGXEfU_yARXEfU_TA + 624
	8   libswiftos.dylib                    0x0000000113c447e1 $Ss12StaticStringV14withUTF8BufferyxxSRys5UInt8VGXElFyt_Tg507$SSRys5F18VGIgy_ACytIegyr_TRAFIgy_Tf1ncn_n + 49
	9   libswiftos.dylib                    0x0000000113c45c8e $S2os0A9_signpost_3dso3log4name0B2ID__ySo0a1_B7_type_ta_SVSo03OS_a1_D0Cs12StaticStringVAA010OSSignpostF0VALs7CVarArg_pdtFySRys5UInt8VGXEfU_TA + 190
	10  libswiftos.dylib                    0x0000000113c447e1 $Ss12StaticStringV14withUTF8BufferyxxSRys5UInt8VGXElFyt_Tg507$SSRys5F18VGIgy_ACytIegyr_TRAFIgy_Tf1ncn_n + 49
	11  libswiftos.dylib                    0x0000000113c453cd $S2os0A9_signpost_3dso3log4name0B2ID__ySo0a1_B7_type_ta_SVSo03OS_a1_D0Cs12StaticStringVAA010OSSignpostF0VALs7CVarArg_pdtF + 317
	12  Kinvey                              0x000000012623c36b $S6Kinvey10RealmCacheC13cascadeDelete5realm10entityType0G012deleteItselfy0B5Swift0B0C_SSAI6ObjectCSbtFTf4nxnnn_n + 1115
	13  Kinvey                              0x0000000126225558 $S6Kinvey10RealmCacheC4save8entities9syncQueryys25AnyRandomAccessCollectionVyxG_AA0G0C5query_10Foundation4DateV8lastSynctSgtFyycfU_y0B5Swift0B0CcfU_yxXEfU_ + 184
	14  Kinvey                              0x000000012623c839 $S6Kinvey10RealmCacheC4save8entities9syncQueryys25AnyRandomAccessCollectionVyxG_AA0G0C5query_10Foundation4DateV8lastSynctSgtFyycfU_y0B5Swift0B0CcfU_yxXEfU_TA + 25
	15  Kinvey                              0x000000012623c874 $Sxs5Error_pIggzo_xsAA_pIegnzo_So8NSObjectCRbz6Kinvey11PersistableRzlTRTA + 20
	16  Kinvey                              0x00000001262e37ef $SST6KinveyE22forEachAutoreleasepoolyyy7ElementQzKXEKFyADKXEfU_yyKXEfU_TA + 31
	17  Kinvey                              0x00000001262d1fdc $Ss5Error_pIgzo_ytsAA_pIegrzo_TR + 12
	18  Kinvey                              0x00000001262e3831 $Ss5Error_pIgzo_ytsAA_pIegrzo_TRTA + 17
	19  libswiftObjectiveC.dylib            0x0000000113b71d7f $S10ObjectiveC15autoreleasepool8invokingxxyKXE_tKlF + 47
	20  Kinvey                              0x00000001262e2f46 $SST6KinveyE22forEachAutoreleasepoolyyy7ElementQzKXEKFyADKXEfU_ + 166
	21  Kinvey                              0x00000001262e3b49 $SST6KinveyE22forEachAutoreleasepoolyyy7ElementQzKXEKFyADKXEfU_TA + 25
	22  libswiftCore.dylib                  0x00000001130de560 $SSTsE7forEachyyy7ElementQzKXEKF + 352
	23  libswiftCore.dylib                  0x000000011312ac2b $SSayxGSTsST7forEachyyy7ElementQzKXEKFTW + 59
	24  libswiftCore.dylib                  0x00000001132eda8e $Ss26_RandomAccessCollectionBoxC8_forEachyyy7ElementQzKXEKF + 126
	25  libswiftCore.dylib                  0x00000001132f16ae $Ss13AnyCollectionV7forEachyyyxKXEKF + 62
	26  libswiftCore.dylib                  0x00000001132f3d3d $Ss25AnyRandomAccessCollectionVyxGSTsST7forEachyyy7ElementQzKXEKFTW + 13
	27  libswiftCore.dylib                  0x00000001133b1227 $SST7forEachyyy7ElementQzKXEKFTj + 7
	28  Kinvey                              0x00000001262dc256 $SST6KinveyE22forEachAutoreleasepoolyyy7ElementQzKXEKF + 118
	29  Kinvey                              0x0000000126225460 $S6Kinvey10RealmCacheC4save8entities9syncQueryys25AnyRandomAccessCollectionVyxG_AA0G0C5query_10Foundation4DateV8lastSynctSgtFyycfU_y0B5Swift0B0CcfU_ + 240
	30  Kinvey                              0x000000012623c7f9 $S6Kinvey10RealmCacheC4save8entities9syncQueryys25AnyRandomAccessCollectionVyxG_AA0G0C5query_10Foundation4DateV8lastSynctSgtFyycfU_y0B5Swift0B0CcfU_TA + 41
	31  Kinvey                              0x000000012623d51f $S6Kinvey10RealmCacheC5write33_86B2BB33C4BBCEC09C15D93A3086D6BALLyyy0B5Swift0B0CKcKFyyKXEfU0_TA + 31
	32  RealmSwift                          0x00000001267d7c15 $S10RealmSwift0A0C5writeyyyyKXEKF + 53
	33  Kinvey                              0x000000012622add3 $S6Kinvey10RealmCacheC5write33_86B2BB33C4BBCEC09C15D93A3086D6BALLyyy0B5Swift0B0CKcKF + 371
	34  Kinvey                              0x000000012622483e $S6Kinvey10RealmCacheC4save8entities9syncQueryys25AnyRandomAccessCollectionVyxG_AA0G0C5query_10Foundation4DateV8lastSynctSgtFyycfU_ + 366
	35  Kinvey                              0x000000012623c909 $S6Kinvey10RealmCacheC4save8entities9syncQueryys25AnyRandomAccessCollectionVyxG_AA0G0C5query_10Foundation4DateV8lastSynctSgtFyycfU_TATm + 25
	36  Kinvey                              0x000000012623c740 $S6Kinvey10RealmCacheC4save8entities9syncQueryys25AnyRandomAccessCollectionVyxG_AA0G0C5query_10Foundation4DateV8lastSynctSgtFyycfU_TA + 16
	37  Kinvey                              0x00000001262d2464 $S6Kinvey8ExecutorC7executeyyyycFyycfU_yyXEfU_TATm + 20
	38  Kinvey                              0x00000001262d2440 $S6Kinvey8ExecutorC14executeAndWaityyyycFyycfU_yyXEfU_TA + 16
	39  Kinvey                              0x00000001262d2549 $S6Kinvey8ExecutorC14executeAndWaityyyycFyycfU_yyXEfU_TA.17 + 9
	40  Kinvey                              0x00000001262d2021 $Ss5Error_pIgzo_ytsAA_pIegrzo_TRTA + 17
	41  Kinvey                              0x00000001262d2539 $Ss5Error_pIgzo_ytsAA_pIegrzo_TRTA.21 + 9
	42  libswiftObjectiveC.dylib            0x0000000113b71d7f $S10ObjectiveC15autoreleasepool8invokingxxyKXE_tKlF + 47
	43  Kinvey                              0x00000001262d23bc $S6Kinvey8ExecutorC14executeAndWaityyyycFyycfU_TA + 140
	44  Kinvey                              0x0000000126215fe0 $SIeg_IeyB_TR + 32
	45  Foundation                          0x0000000110660f9e __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	46  Foundation                          0x0000000110660ea5 -[NSBlockOperation main] + 68
	47  Foundation                          0x000000011065dc14 -[__NSOperationInternal _start:] + 689
	48  Foundation                          0x0000000110663c4b __NSOQSchedule_f + 227
	49  libdispatch.dylib                   0x0000000119e85046 _dispatch_block_async_invoke2 + 83
	50  libdispatch.dylib                   0x0000000119e77602 _dispatch_client_callout + 8
	51  libdispatch.dylib                   0x0000000119e8499a _dispatch_main_queue_callback_4CF + 1541
	52  CoreFoundation                      0x00000001115ba3e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	53  CoreFoundation                      0x00000001115b4a76 __CFRunLoopRun + 2342
	54  CoreFoundation                      0x00000001115b3e11 CFRunLoopRunSpecific + 625
	55  GraphicsServices                    0x00000001157a51dd GSEventRunModal + 62
	56  UIKitCore                           0x00000001203ea81d UIApplicationMain + 140
	57  muvr                                0x000000010cdd0fc7 main + 71
	58  libdyld.dylib                       0x0000000119eed575 start + 1
	59  ???                                 0x0000000000000001 0x0 + 1
)
```

### Steps to reproduce 
Not sure, it seems to be data related as I can get it to crash 100% of the time on multiple simulators (iPhone 8, iPhone XS, both running iOS 12.1) - apps on both simulators are logged in to the same user account.

### Kinvey SDK Version
3.21.0

### Tool Versions (XCode / Swift / iOS / Device)
Xcode 10.1, Swift 4.2, iOS 12.1, iPhone 8/XS simulators

**Comment by tzuhaohuang** [comment] 2019-01-04 21:42
It happened to me too. But it happened when I was trying to use DataStore.save().

![screen shot 2019-01-04 at 4 36 26 pm](https://user-images.githubusercontent.com/18216145/50712328-16063380-103f-11e9-8d2a-f3ef337f892c.png)

Log:
2019-01-04 16:38:36.345085-0500 -[Swift._SwiftDeferredNSArray UTF8String]: unrecognized selector sent to instance 0x283254960
-[Swift._SwiftDeferredNSArray UTF8String]: unrecognized selector sent to instance 0x283254960
(null)


Kinvey SDK Version

3.21.0

Tool Versions (XCode / Swift / iOS / Device)

Xcode 10.1, Swift 4.2, iOS 12.0, iPhone X

**Comment by heyzooi** [comment] 2019-01-04 23:14
@ifabijanovic and @tzuhaohuang we were not not able to reproduce this issue. Reading the logs I create a PR with some changes that I believe that can fix the problem, so could you please test again against the `feature/crash_bugfix_signpost` branch?

To do that (if you are using CocoaPods) you can clone this repo change the branch and add `pod 'Kinvey', :path => '<path for the swift-sdk repo>'` to your `Podfile`

Please let me know the results.

**Comment by tzuhaohuang** [comment] 2019-01-07 16:24
Hi, Victor.

Sadly it still happened.
![screen shot 2019-01-07 at 11 19 35 am](https://user-images.githubusercontent.com/18216145/50779438-4e3f8900-126e-11e9-8202-6c5fe70fc721.png)

If I click "Continue Program Execution", Xcode will jump to line 45 in Kinvey.Swift as "Thread 1: breakpoint 1.1 3.1". Not sure if this information can help.

Kinvey SDK Version

3.21.0 (branch: feature/crash_bugfix_signpost)

Tool Versions (XCode / Swift / iOS / Device)

Xcode 10.1, Swift 4.2, iOS 12.0 on device, iPhone X

And our app's minimum deployment target is iOS 11.

Thanks

**Comment by heyzooi** [comment] 2019-01-07 23:34
@tzuhaohuang I just pushed a new commit, could you please run `git pull` in the branch and try again please. I was able to reproduce locally and now it seems the issue is fixed.

**Comment by tzuhaohuang** [comment] 2019-01-08 15:49
Hi, Victor.

Good news, it works for my test case (DataStore.save())

Thanks for the help!

**Comment by heyzooi** [comment] 2019-01-08 18:40
awesome! thanks for the feedback @tzuhaohuang! the PR will now be peer-reviewed and the fix will be in the next release. I will close this issue once the release is officially out.

**Closed as completed** 2019-01-15 20:33 UTC
